workflows:
  build-termux:
    name: Build Termux APK
    max_build_duration: 30
    environment:
      vars:
        NDK_VERSION: 25.2.9519653
      java: 17
    scripts:
      - name: Setup local.properties
        script: |
          echo "ndk.dir=/usr/local/share/android-sdk/ndk/25.2.9519653" >> local.properties
      - name: Install NDK
        script: |
          yes | ${ANDROID_SDK_ROOT}/cmdline-tools/latest/bin/sdkmanager "ndk;$NDK_VERSION"
      - name: Make gradlew executable
        script: chmod +x ./gradlew

      - name: Build APK
        script: |
          cd shell
          ./gradlew assembleRelease -Dorg.gradle.jvmargs="--add-opens java.base/java.io=ALL-UNNAMED" --scan
    publishing:
      email:
        recipients:
          - avalubau@gmail.com
        notify:
          success: true
          failure: false

    artifacts:
      - app/build/outputs/**/*.aab
      - app/build/outputs/**/*.apk
      - termux-app/build/**/outputs/apk/**/*.apk
      - build/**/outputs/apk/**/*.apk
      - subfolder_name/build/**/outputs/apk/**/*.apk
      - build/**/outputs/**/*.aab
      - build/**/outputs/**/mapping.txt
      - build/ios/ipa/*.ipa
      - build/macos/**/*.pkg
      - /tmp/xcodebuild_logs/*.log
      - flutter_drive.log
