workflows:
  build-termux:
    name: Build Termux APK
    max_build_duration: 30
    environment:
      vars:
        NDK_VERSION: 25.2.9519653
      java: 17
    scripts:
      - name: Install NDK
        script: |
          yes | ${ANDROID_SDK_ROOT}/cmdline-tools/latest/bin/sdkmanager "ndk;$NDK_VERSION"
      - name: Make gradlew executable
        script: chmod +x ./gradlew

      - name: Build APK
        script: ./gradlew assembleDebug -Dorg.gradle.jvmargs="--add-opens java.base/java.io=ALL-UNNAMED" --scan
    artifacts:
      - app/build/outputs/apk/debug/app-debug.apk
