workflows:
  build-termux:
    name: Build Termux APK
    max_build_duration: 30
    environment:
      vars:
        NDK_VERSION: 25.2.9519653
      java: 17
    scripts:
      - name: Setup local.properties
        script: |
          echo "ndk.dir=/usr/local/share/android-sdk/ndk/25.2.9519653" >> local.properties
      - name: Install NDK
        script: |
          yes | ${ANDROID_SDK_ROOT}/cmdline-tools/latest/bin/sdkmanager "ndk;$NDK_VERSION"
      - name: Make gradlew executable
        script: chmod +x ./gradlew

      - name: Build APK
        script: ./gradlew assembleDebug -Dorg.gradle.jvmargs="--add-opens java.base/java.io=ALL-UNNAMED" --scan
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
      - build/app/outputs/bundle/release/app-release.aab
      - build/ios/ipa/*.ipa
